[tox]
envlist = yamllint,markdownlint

[testenv]
skip_install = True

[testenv:gitlint]
envdir = {toxworkdir}/gitlint
deps = gitlint
commands = gitlint {posargs}

[testenv:yamllint]
envdir = {toxworkdir}/yamllint
deps = yamllint
commands = yamllint {toxinidir}

[testenv:markdownlint]
envdir = {toxworkdir}/markdownlint
deps = pymarkdownlnt
commands = pymarkdown -c .pymarkdown.json scan --respect-gitignore -r .
